CREATE EXTENSION unaccent;

CREATE FUNCTION remove_accents(TEXT) RETURNS TEXT
    LANGUAGE sql
    IMMUTABLE STRICT AS
'SELECT unaccent(lower($1))';

CREATE FUNCTION extract_days(DATE) returns INT
    LANGUAGE sql
    IMMUTABLE STRICT AS
'SELECT (CURRENT_DATE - $1)'